# Tox config file
# See https://tox.wiki/en/latest/config.html

[tox]
envlist = py{39,310,311,312}, ruff

[testenv]
deps =
    pytest
    pytest-sugar
commands = pytest

[testenv:ruff]
setenv = RUFF_CACHE_DIR={env:TMPDIR}/ruff_cache
deps = ruff
commands = ruff check .
basepython = python3
skip_install = true
